# Generated by Django 3.1.4 on 2021-01-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_uploaded', to='book_app.user')),
                ('user_who_like', models.ManyToManyField(related_name='liked_book', to='book_app.User')),
            ],
        ),
    ]
