# Generated by Django 3.1.4 on 2021-01-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='no'),
            preserve_default=False,
        ),
    ]
